
package Frame;

import Repositorios.PostRepository;
import Repositorios.UsuarioRepository;
import com.mongodb.client.MongoDatabase;
import entity.Comentario;
import entity.Post;
import entity.Usuario;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Estefanía Aguilar
 */
public class Publicacion extends javax.swing.JPanel {
    public static final String newline = "\n";
    Post post;
    PostRepository postRepository;    
    Usuario usuario;
    UsuarioRepository usuarioRepository;
    List<Comentario> comentarios;    
    
    public Publicacion(Post post, Usuario usuario) {
        initComponents();         
        this.post = post;              
        this.usuario = usuario;        
        
        comentarios = this.post.getComentarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAComentarios = new javax.swing.JTextArea();
        lblPublicacion = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        txtComentario = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAComentarios.setEditable(false);
        txtAComentarios.setColumns(20);
        txtAComentarios.setRows(5);
        jScrollPane1.setViewportView(txtAComentarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 320, 80));

        lblPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblPublicacionActionPerformed(evt);
            }
        });
        add(lblPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 320, 90));

        lblNombre.setForeground(new java.awt.Color(51, 51, 51));
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 103, 22));
        add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 60, 20));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/avatar.png"))); // NOI18N
        add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 40));

        txtComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComentarioActionPerformed(evt);
            }
        });
        txtComentario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtComentarioKeyPressed(evt);
            }
        });
        add(txtComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 250, 30));

        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/send.png"))); // NOI18N
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 60, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blancosolido.jpg"))); // NOI18N
        add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void lblPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblPublicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPublicacionActionPerformed

    private void txtComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComentarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComentarioActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if(validarComentario()){
            
            Comentario comentario = new Comentario (txtComentario.getText(), this.usuario, new Date());
            
            SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a dd-MMMM-yyyy");
            
            txtAComentarios.append(comentario.getUsuario().getNombre() + ": " + comentario.getTexto() + newline 
                    + "     " +formater.format(comentario.getFechaHora())+ newline);
            txtComentario.selectAll();
            txtAComentarios.setCaretPosition(txtAComentarios.getDocument().getLength());
            
            this.comentarios.add(comentario);            
            this.post.setComentarios(comentarios);
            //postRepository.actualizar(database, this.post);
            //usuarioRepository.actualizar(database, this.usuario);
            
            txtComentario.setText("");
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtComentarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComentarioKeyPressed
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                if(validarComentario()){
                    Comentario comentario = new Comentario (txtComentario.getText(), this.usuario, new Date());
            
            SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a dd-MMMM-yyyy");
            
            txtAComentarios.append(comentario.getUsuario().getNombre() + ": " + comentario.getTexto() + newline 
                    + "     " +formater.format(comentario.getFechaHora())+ newline);
            txtComentario.selectAll();
            txtAComentarios.setCaretPosition(txtAComentarios.getDocument().getLength());
            
            this.comentarios.add(comentario);
            this.post.setComentarios(comentarios);
            //postRepository.actualizar(database, this.post);
            //usuarioRepository.actualizar(database, this.usuario);
            
            txtComentario.setText("");
                }
            }
    }//GEN-LAST:event_txtComentarioKeyPressed

    public boolean validarComentario() {
        if (!txtComentario.getText().isEmpty()){
            for(int i =0; i<txtComentario.getText().length(); i++){
                 if(txtComentario.getText().charAt(i) != ' '){
                     return true;
                 }
            }            
        }
        return false;        
    }
    
    public void mostrarDatos() {
        lblNombre.setEnabled(false);
        lblFecha.setEnabled(false);
        lblNombre.setText(post.getUsuario().getNombre());
        lblFecha.setText(post.getFechaHora().toString());
        txtAComentarios.setEnabled(false);                        
       
        if (!post.getComentarios().isEmpty()) {
            for (Comentario comentario : post.getComentarios()) {                                
                SimpleDateFormat formater = new SimpleDateFormat("hh: mm: ss a dd-MMMM-yyyy");                
                txtAComentarios.append(comentario.getUsuario().getNombre() + ": " + comentario.getTexto() + newline 
                        + "     " + formater.format(comentario.getFechaHora())
                        +newline);
                txtAComentarios.selectAll();
                txtAComentarios.setCaretPosition(txtAComentarios.getDocument().getLength());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField lblPublicacion;
    private javax.swing.JTextArea txtAComentarios;
    private javax.swing.JTextField txtComentario;
    // End of variables declaration//GEN-END:variables
}
